
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'PIF THEN ELSE DEF INTEGER ID OP_REL OP_ADD OP_MULT COMMENT EQ SEMI COL LPAREN RPAREN P : ID EQ INTEGER SEMI P\n          | I\n     I : D I\n          | D\n     D : DEF ID LPAREN ARGS RPAREN EQ E SEMI\n     ARGS : ID COL ARGS\n             | ID\n     SEQ : E COL SEQ\n            | E\n     E : INTEGER\n          | ID\n          | IF E OP_REL E THEN E ELSE E\n          | ARIT_EXP\n          | ID LPAREN SEQ RPAREN\n     ARIT_EXP : ARIT_EXP OP_ADD TERM\n                 | TERM\n     TERM : TERM OP_MULT FACTOR\n             | FACTOR\n     FACTOR : PAREN\n               | E\n     PAREN : LPAREN E RPAREN\n    '
    
_lr_action_items = {'COL':([12,19,20,22,24,25,27,34,37,38,39,40,42,48,],[15,-19,-18,-10,-11,-16,-13,-21,43,-17,-20,-15,-14,-12,]),'DEF':([0,5,13,32,],[2,2,2,-5,]),'LPAREN':([6,17,21,23,24,30,31,33,35,43,44,47,],[9,21,21,21,30,21,21,21,21,21,21,21,]),'SEMI':([10,19,20,22,24,25,26,27,34,38,39,40,42,48,],[13,-19,-18,-10,-11,-16,32,-13,-21,-17,-20,-15,-14,-12,]),'THEN':([19,20,22,24,25,27,34,38,39,40,41,42,48,],[-19,-18,-10,-11,-16,-13,-21,-17,-20,-15,44,-14,-12,]),'OP_ADD':([19,20,22,24,25,26,27,28,29,34,37,38,39,40,41,42,46,48,],[-19,-18,-10,-11,-16,-20,33,-20,-20,-21,-20,-17,-20,-15,-20,-14,-20,-12,]),'IF':([17,21,23,30,31,33,35,43,44,47,],[23,23,23,23,23,23,23,23,23,23,]),'ID':([0,2,9,13,15,17,21,23,30,31,33,35,43,44,47,],[3,6,12,3,12,24,24,24,24,24,24,24,24,24,24,]),'OP_MULT':([19,20,22,24,25,26,27,28,29,34,37,38,39,40,41,42,46,48,],[-19,-18,-10,-11,31,-20,-13,-20,-20,-21,-20,-17,-20,31,-20,-14,-20,-12,]),'OP_REL':([19,20,22,24,25,27,29,34,38,39,40,42,48,],[-19,-18,-10,-11,-16,-13,35,-21,-17,-20,-15,-14,-12,]),'$end':([1,4,5,8,16,32,],[-2,0,-4,-3,-1,-5,]),'INTEGER':([7,17,21,23,30,31,33,35,43,44,47,],[10,22,22,22,22,22,22,22,22,22,22,]),'EQ':([3,14,],[7,17,]),'ELSE':([19,20,22,24,25,27,34,38,39,40,42,46,48,],[-19,-18,-10,-11,-16,-13,-21,-17,-20,-15,-14,47,-12,]),'RPAREN':([11,12,18,19,20,22,24,25,27,28,34,36,37,38,39,40,42,45,48,],[14,-7,-6,-19,-18,-10,-11,-16,-13,34,-21,42,-9,-17,-20,-15,-14,-8,-12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'I':([0,5,13,],[1,8,1,]),'D':([0,5,13,],[5,5,5,]),'SEQ':([30,43,],[36,45,]),'TERM':([17,21,23,30,31,33,35,43,44,47,],[25,25,25,25,25,40,25,25,25,25,]),'E':([17,21,23,30,31,33,35,43,44,47,],[26,28,29,37,39,39,41,37,46,48,]),'PAREN':([17,21,23,30,31,33,35,43,44,47,],[19,19,19,19,19,19,19,19,19,19,]),'ARIT_EXP':([17,21,23,30,31,33,35,43,44,47,],[27,27,27,27,27,27,27,27,27,27,]),'ARGS':([9,15,],[11,18,]),'FACTOR':([17,21,23,30,31,33,35,43,44,47,],[20,20,20,20,38,20,20,20,20,20,]),'P':([0,13,],[4,16,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> P","S'",1,None,None,None),
  ('P -> ID EQ INTEGER SEMI P','P',5,'p_P','main.py',66),
  ('P -> I','P',1,'p_P','main.py',67),
  ('I -> D I','I',2,'p_I','main.py',76),
  ('I -> D','I',1,'p_I','main.py',77),
  ('D -> DEF ID LPAREN ARGS RPAREN EQ E SEMI','D',8,'p_D','main.py',86),
  ('ARGS -> ID COL ARGS','ARGS',3,'p_ARGS','main.py',92),
  ('ARGS -> ID','ARGS',1,'p_ARGS','main.py',93),
  ('SEQ -> E COL SEQ','SEQ',3,'p_SEQ','main.py',102),
  ('SEQ -> E','SEQ',1,'p_SEQ','main.py',103),
  ('E -> INTEGER','E',1,'p_E','main.py',112),
  ('E -> ID','E',1,'p_E','main.py',113),
  ('E -> IF E OP_REL E THEN E ELSE E','E',8,'p_E','main.py',114),
  ('E -> ARIT_EXP','E',1,'p_E','main.py',115),
  ('E -> ID LPAREN SEQ RPAREN','E',4,'p_E','main.py',116),
  ('ARIT_EXP -> ARIT_EXP OP_ADD TERM','ARIT_EXP',3,'p_ARIT_EXP','main.py',125),
  ('ARIT_EXP -> TERM','ARIT_EXP',1,'p_ARIT_EXP','main.py',126),
  ('TERM -> TERM OP_MULT FACTOR','TERM',3,'p_TERM','main.py',135),
  ('TERM -> FACTOR','TERM',1,'p_TERM','main.py',136),
  ('FACTOR -> PAREN','FACTOR',1,'p_FACTOR','main.py',145),
  ('FACTOR -> E','FACTOR',1,'p_FACTOR','main.py',146),
  ('PAREN -> LPAREN E RPAREN','PAREN',3,'p_PAREN','main.py',152),
]
